### PR TITLE
Fee transfer reentrancy

### PR DESCRIPTION
**Pull request by CalabashSquash**
Fix #463

### CODE REVIEW

**Comment by chrdevmar** [comment]
are you sure thats right that `lastPriceTimestamp` will always be at least `block.timestamp`? I thought that the code now updated to be as far as the iterations on upkeeps would go with the capped iterations?

ie if we were 18 hours overdue for upkeep, `lastPriceTimestamp` would end up being ~3 hours ago since `MAX_ITERATIONS` is 15 (assuming an `updateInterval` of 1 hour)

**Comment by CalabashSquash** [comment]
Yep, comment was wrong. This is a sigma-approved (TM) fix though, but if you have any doubts about it pls LMK.

**Comment by chrdevmar** [comment]
Ah I get it now, will be set to whatever the correct value is (potentially in the past like I said in my comment) by the end of the transaction

**Comment by CalabashSquash** [comment]
Yep that's correct

**Review by chrdevmar — APPROVED** [review]

**Review by sporejack — APPROVED** [review]

**Pull request merged**
